#!/usr/bin/env bash
# Provision a freshly-flashed camera with its WireGuard identity.
#
# Usage:
#   tools/provision-camera.sh <cam-ip> <wg-easy-config.conf> [cam-user]
#
# Inputs:
#   <cam-ip>              IP the camera is currently reachable at (LAN, before
#                         WG is up). Default user is root.
#   <wg-easy-config.conf> Per-camera config downloaded from wg-easy UI ("Add
#                         Client" → download). Contains the camera's unique
#                         PrivateKey, Address, and the VPS [Peer] block.
#
# What it does:
#   1. Parses the wg-easy config.
#   2. Writes /etc/wireguard.conf in `wg setconf` format (PrivateKey + Peer,
#      no Address — that lives in ifupdown).
#   3. Writes /etc/network/interfaces.d/wg0 with the camera's Address.
#   4. Brings the interface down/up.
#   5. Pings the VPS (10.8.0.1) over wg0 to confirm handshake.
#
# Re-running on the same camera replaces its identity; safe.
set -euo pipefail

if [[ $# -lt 2 ]]; then
    echo "usage: $0 <cam-ip> <wg-easy-config.conf> [cam-user]" >&2
    exit 1
fi

CAM_IP=$1
CONF=$2
USER=${3:-root}

[[ -r "$CONF" ]] || { echo "cannot read $CONF" >&2; exit 1; }

# ── Parse the wg-easy config ──────────────────────────────────────────────────
# Pull PrivateKey, Address from [Interface], and the entire [Peer] block.
# WireGuard keys end with '=' (base64 padding) — split on the FIRST '=' only.
ifield() { awk -v k="$1" '/^\[Interface\]/{i=1;next} /^\[/{i=0} i && $0 ~ "^"k"[ \t]*="{sub(/^[^=]*=[ \t]*/,""); print; exit}' "$CONF"; }
PRIVATE_KEY=$(ifield PrivateKey)
ADDRESS=$(ifield Address)
PEER_BLOCK=$(awk '/^\[Peer\]/{p=1} p{print}' "$CONF")

[[ -n $PRIVATE_KEY ]] || { echo "no PrivateKey found in $CONF" >&2; exit 1; }
[[ -n $ADDRESS ]]     || { echo "no Address found in $CONF" >&2; exit 1; }
[[ -n $PEER_BLOCK ]]  || { echo "no [Peer] block found in $CONF" >&2; exit 1; }

# Address may be "10.8.0.5/24" — split into IP + CIDR for ifupdown.
WG_IP=${ADDRESS%%/*}
WG_CIDR=${ADDRESS##*/}
[[ "$WG_CIDR" != "$ADDRESS" ]] || WG_CIDR=24
WG_NETMASK=$(python3 -c "import ipaddress; print(ipaddress.ip_network(f'0.0.0.0/$WG_CIDR').netmask)" 2>/dev/null \
             || echo 255.255.255.0)

# ── Build the two camera-side files in a tmpdir ───────────────────────────────
TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

cat > "$TMP/wireguard.conf" <<EOF
# Generated by tools/provision-camera.sh from $(basename "$CONF")
[Interface]
PrivateKey = $PRIVATE_KEY

$PEER_BLOCK
EOF

cat > "$TMP/wg0" <<EOF
auto wg0
iface wg0 inet static
    address $WG_IP
    netmask $WG_NETMASK
    pre-up modprobe wireguard
    pre-up ip link add dev wg0 type wireguard
    pre-up wg setconf wg0 /etc/wireguard.conf
    post-down ip link del dev wg0
EOF

# ── Ship and apply ────────────────────────────────────────────────────────────
echo "→ pushing config to $USER@$CAM_IP (wg ip $WG_IP/$WG_CIDR)"
scp -q "$TMP/wireguard.conf" "$USER@$CAM_IP:/etc/wireguard.conf"
scp -q "$TMP/wg0"            "$USER@$CAM_IP:/etc/network/interfaces.d/wg0"

ssh "$USER@$CAM_IP" "chmod 600 /etc/wireguard.conf && ifdown wg0 2>/dev/null; ifup wg0"

echo "→ verifying handshake to 10.8.0.1"
if ssh "$USER@$CAM_IP" 'for i in $(seq 1 10); do ping -c1 -W1 10.8.0.1 >/dev/null 2>&1 && exit 0; sleep 1; done; exit 1'; then
    echo "✓ camera $CAM_IP reachable at $WG_IP via WireGuard"
else
    echo "✗ no handshake after 10s. Check:" >&2
    echo "    ssh $USER@$CAM_IP 'wg show wg0; ip route; ping -c1 1.1.1.1'" >&2
    exit 2
fi
